# 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력
#BOOK A
#AUTHOR B
##BOOK_SALES  C  

SELECT C.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY , SUM(B.SALES * A.PRICE) TOTAL_SALES
FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID 
JOIN AUTHOR C ON A.AUTHOR_ID = C.AUTHOR_ID
WHERE DATE_FORMAT(B.SALES_DATE ,'%Y%m') = 202201
GROUP BY C.AUTHOR_ID , A.CATEGORY
ORDER BY C.AUTHOR_ID asc, A.CATEGORY desc ;