SELECT ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN  (
SELECT A.ITEM_ID
FROM ITEM_INFO A LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.PARENT_ITEM_ID IS NOT NULL 
GROUP BY A.ITEM_ID
)
ORDER BY ITEM_ID desc; 
