# ONLINE_SALE  어느 의류 쇼핑몰의 온라인 상품 판매 정보
# OFFLINE_SALE  오프라인 상품 판매 정보
# ONLINE_SALE 테이블과 OFFLINE_SALE 테이블에서 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량을 출력
SELECT *
FROM ( 
SELECT DATE_FORMAT(SALES_DATE , '%Y-%m-%d') SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE A
WHERE DATE_FORMAT(SALES_DATE , '%Y-%m') = '2022-03'
UNION ALL 
SELECT DATE_FORMAT(SALES_DATE , '%Y-%m-%d') SALES_DATE,PRODUCT_ID, NULL  USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE , '%Y-%m') = '2022-03'
) uni
ORDER BY SALES_DATE,PRODUCT_ID,USER_ID;