SELECT C.ANIMAL_ID , C.NAME
FROM 
(SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME IS NOT NULL AND B.DATETIME IS NOT NULL
ORDER BY (B.DATETIME-A.DATETIME) desc 
) C
WHERE ROWNUM <= 2;