--  중고 거래 게시물을 3건 이상 등록한 사용자의 사용자 ID, 닉네임, 전체주소, 전화번호
SELECT USER_ID , NICKNAME , CITY ||' '|| STREET_ADDRESS1||' '||STREET_ADDRESS2 전체주소,
        SUBSTR( TLNO , 0, 3) || '-'|| SUBSTR( TLNO , 4, 4)  ||'-'|| SUBSTR( TLNO , 8) 전화번호
FROM USED_GOODS_USER 
WHERE (USER_ID) IN (
SELECT A.WRITER_ID USER_ID
FROM USED_GOODS_BOARD A LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(*) >=3 
)
ORDER BY USER_ID desc ;