-- 서울에 위치한 식당들의 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수를 조회
-- 식당의 정보를 담은 REST_INFO 테이블
-- 리뷰 정보를 담은 REST_REVIEW 테이블
SELECT A.REST_ID , A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND( AVG(REVIEW_SCORE) , 2 ) SCORE 
FROM REST_INFO A JOIN REST_REVIEW B ON A.REST_ID = B.REST_ID
WHERE SUBSTR(A.ADDRESS ,0,2) = '서울'
GROUP BY A.REST_ID , A.REST_NAME, A.FOOD_TYPE, A.FAVORITES,  A.ADDRESS
ORDER BY SCORE desc , FAVORITES desc ; 