-- 의류 쇼핑몰에 가입한 회원 정보를 담은 USER_INFO 테이블
-- 온라인 상품 판매 정보를 담은 ONLINE_SALE 테이블
-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계
SELECT YEAR(B.SALES_DATE) ,  MONTH(B.SALES_DATE) , A.GENDER, COUNT(DISTINCT B.USER_ID) USERS
FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL 
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER;