# SELECT fp.PRODUCT_ID , fp.PRODUCT_NAME, (fp.PRICE * fo.AMOUNT) 'TOTAL_SALES'
# FROM FOOD_PRODUCT fp
# JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
# WHERE DATE_FORMAT ( fo.PRODUCE_DATE, '%Y') = 2022 AND DATE_FORMAT ( fo.PRODUCE_DATE, '%m') = 5
# GROUP BY fp.PRODUCT_ID
# ORDER BY `TOTAL_SALES` desc, fp.PRODUCT_ID;

SELECT fp.PRODUCT_ID , fp.PRODUCT_NAME, (fp.PRICE * SUM(fo.AMOUNT)) 'TOTAL_SALES'
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE DATE_FORMAT ( fo.PRODUCE_DATE, '%Y') = 2022 AND DATE_FORMAT ( fo.PRODUCE_DATE, '%m') = 5
GROUP BY fp.PRODUCT_ID ,fp.PRODUCT_NAME
ORDER BY `TOTAL_SALES` desc, fp.PRODUCT_ID;
