SELECT a.*
FROM (

SELECT f.FLAVOR , SUM(f.TOTAL_ORDER+j.TOTAL_ORDER) 'AMOUNT'
FROM FIRST_HALF f
JOIN JULY j ON f.FLAVOR = j.FLAVOR
GROUP BY f.FLAVOR 
ORDER BY `AMOUNT` desc 
    
    ) a


# SELECT *
# FROM FIRST_HALF f
# JOIN JULY j ON f.FLAVOR = j.FLAVOR
# GROUP BY f.FLAVOR ; 