SELECT A.APNT_NO , B.PT_NAME, A.PT_NO , A.MCDP_CD, C.DR_NAME, APNT_YMD
FROM APPOINTMENT A LEFT JOIN PATIENT  B ON A.PT_NO = B.PT_NO
JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE DATE_FORMAT(APNT_YMD , '%Y%m%d') = 20220413 AND A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;