# ANIMAL_OUTS 테이블은 동물 보호소에서 입양 보낸 동물의 정보를 담은 테이블
# SELECT '0' HOUR
# FROM DUAL
# UNION ALL 
# SELECT '1' HOUR
# FROM DUAL
WITH RECURSIVE hours AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1
    FROM hours
    WHERE hour < 23
)
SELECT A.HOUR , IFNULL( COUNT , 0)
FROM hours A LEFT JOIN (
SELECT HOUR(DATETIME) HOUR , COUNT(*) COUNT
FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)
    ) B ON A.HOUR = B.HOUR ; 

