#  2022년도 한해 평가 점수가 가장 높은 사원 정보
SELECT B.SCORE , A.EMP_NO , A.EMP_NAME , A.POSITION , A.EMAIL
FROM HR_EMPLOYEES  A
JOIN (
SELECT EMP_NO , SUM(SCORE) SCORE
FROM HR_GRADE
GROUP BY EMP_NO
ORDER BY SCORE desc
LIMIT 1
    ) B ON A.EMP_NO = B.EMP_NO;
