WITH A AS (
SELECT BOOK_ID , SUM(SALES) SALES
FROM BOOK_SALES 
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BOOK_ID
)

SELECT BO.category CATEGORY , SUM(SALES) TOTAL_SALES
FROM BOOK BO JOIN A 
ON BO.BOOK_ID = A.BOOK_ID
GROUP BY BO.category
ORDER BY CATEGORY;